#!/usr/bin/env bash
#
# Fetches the current Gemini model list from the API and updates
# internal/config/known_models.go with text-capable 3.1 models.
#
# Usage:
#   ./scripts/update-models.sh
#   # Reads the Gemini API key from ~/.config/prr/config.json
#
# The script filters out non-text models (image, TTS, computer-use, robotics,
# embeddings, custom-tools) and only keeps models that support generateContent
# with >= 100K input context.
#
set -euo pipefail

# Read Gemini API key from config.json
CONFIG_FILE="${HOME}/.config/prr/config.json"
if [ ! -f "$CONFIG_FILE" ]; then
  echo "error: $CONFIG_FILE not found — configure the app first" >&2
  exit 1
fi

KEY=$(python3 -c "
import json, sys
try:
    cfg = json.load(open('$CONFIG_FILE'))
    print(cfg.get('providers', {}).get('gemini', {}).get('api_key', ''))
except Exception:
    pass
")

if [ -z "$KEY" ]; then
  echo "error: no gemini API key found in $CONFIG_FILE" >&2
  echo "  Add it under providers.gemini.api_key" >&2
  exit 1
fi

API_URL="https://generativelanguage.googleapis.com/v1beta/models?key=${KEY}"
TARGET="internal/config/known_models.go"

if [ ! -f "$TARGET" ]; then
  echo "error: $TARGET not found — run from repo root" >&2
  exit 1
fi

echo "Fetching models from Gemini API..."

MODELS_JSON=$(curl -sf "$API_URL") || {
  echo "error: failed to fetch models from API" >&2
  exit 1
}

# Generate the Go model entries from the API response
GEMINI_ENTRIES=$(echo "$MODELS_JSON" | python3 -c "
import json, sys

data = json.load(sys.stdin)
models = data.get('models', [])

# Filter: 3.1 family, text generation capable, large context
SKIP_KEYWORDS = ['image', 'tts', 'computer-use', 'robotics', 'embedding', 'customtools', 'live', 'research']

text_models = []
for m in models:
    mid = m['name'].replace('models/', '')
    if not ('3.1' in mid or mid.startswith('gemini-3-')):
        continue
    methods = m.get('supportedGenerationMethods', [])
    if 'generateContent' not in methods:
        continue
    if m.get('inputTokenLimit', 0) < 100000:
        continue
    if any(kw in mid for kw in SKIP_KEYWORDS):
        continue
    text_models.append({
        'id': mid,
        'display': m.get('displayName', mid),
        'input_limit': m.get('inputTokenLimit', 0),
        'output_limit': m.get('outputTokenLimit', 0),
    })

# Sort: pro before flash, stable before preview
def sort_key(m):
    mid = m['id']
    family = 0
    tier = 0 if '-pro' in mid else (1 if 'flash-lite' not in mid and 'flash' in mid else 2)
    preview = 1 if 'preview' in mid else 0
    return (family, tier, preview, mid)

text_models.sort(key=sort_key)

# Classify models for AOI and Review roles
# Pro models: review only. Flash/Flash-Lite: review + AOI.
# Lite-only models without thinking: AOI only.
for m in text_models:
    mid = m['id']
    is_pro = '-pro' in mid
    is_lite = 'lite' in mid
    is_31 = '3.1' in mid

    # Role assignment
    m['review'] = True  # all text models can review
    m['aoi'] = is_lite  # lite models are AOI-suitable
    m['thinking'] = is_pro or is_31

    # Speed estimate
    if is_lite:
        m['speed'] = 'fast'
    elif is_pro:
        m['speed'] = 'slow'
    else:
        m['speed'] = 'medium'

# Print Go struct literals
for m in text_models:
    flags = []
    if m['thinking']:
        flags.append('Thinking: true')
    if m['review']:
        flags.append('Review: true')
    if m['aoi']:
        flags.append('AOI: true')
    flags_str = ', '.join(flags)

    # We can't get pricing from the API, so use placeholder 0.00
    print(f'\t{{ID: \"{m[\"id\"]}\", Label: \"{m[\"display\"]}\", Provider: \"gemini\", {flags_str},')
    print(f'\t\tInputPricePer1M: 0.00, OutputPricePer1M: 0.00, Speed: \"{m[\"speed\"]}\"}},')
")

if [ -z "$GEMINI_ENTRIES" ]; then
  echo "error: no text models found from API" >&2
  exit 1
fi

echo ""
echo "Found Gemini text models:"
echo "$GEMINI_ENTRIES"
echo ""

# Build the new models block
NEW_BLOCK="// knownModels is the canonical list of supported models.
// Order matters — it determines picker display order.
//
// Gemini models are auto-generated by scripts/update-models.sh.
// Pricing must be updated manually — the API does not provide it.
var knownModels = []KnownModel{
	// ── Gemini (auto-generated, pricing manual) ─────────────────────────
${GEMINI_ENTRIES}
	// ── Anthropic ───────────────────────────────────────────────────────
	{ID: \"claude-sonnet-4-20250514\", Label: \"Claude Sonnet 4\", Provider: \"anthropic\", Thinking: true, Review: true,
		InputPricePer1M: 3.00, OutputPricePer1M: 15.00, Speed: \"medium\"},
	{ID: \"claude-haiku-3-5\", Label: \"Claude Haiku 3.5\", Provider: \"anthropic\", AOI: true,
		InputPricePer1M: 0.80, OutputPricePer1M: 4.00, Speed: \"fast\"},

	// ── OpenAI ──────────────────────────────────────────────────────────
	{ID: \"gpt-4o\", Label: \"GPT-4o\", Provider: \"openai\", Review: true,
		InputPricePer1M: 2.50, OutputPricePer1M: 10.00, Speed: \"medium\"},
	{ID: \"gpt-4o-mini\", Label: \"GPT-4o Mini\", Provider: \"openai\", AOI: true,
		InputPricePer1M: 0.15, OutputPricePer1M: 0.60, Speed: \"fast\"},
}"

# Replace the knownModels block in the Go file using python for reliable multiline replace
python3 -c "
import re, sys

with open('$TARGET', 'r') as f:
    content = f.read()

# Match from 'var knownModels' to the closing '}'
pattern = r'// knownModels is the canonical list.*?^}'
new_block = sys.stdin.read()

result = re.sub(pattern, new_block, content, count=1, flags=re.DOTALL | re.MULTILINE)

with open('$TARGET', 'w') as f:
    f.write(result)
" <<< "$NEW_BLOCK"

echo "Updated $TARGET"
echo ""
echo "IMPORTANT: Pricing is set to 0.00 for new models — update manually!"
echo ""

# Format
if command -v gofmt &>/dev/null; then
  gofmt -w "$TARGET"
  echo "Formatted with gofmt"
fi
